# UC San Diego: Data Science in Practice - EDA Checkpoint
### Summer Session I 2023 | Instructor : C. Alex Simpkins Ph.D.

## Draft project title if you have one (can be changed later)

(This checkpoint helps you to perform your EDA on your data for your project. You can remove this text description. Consider this the next step in your final project. See the project readme for bullet points to check off in terms of details to include beyond the main section heading content below.)

# Names

- Dave Santos
- Jose Ortega

<a id='research_question'></a>
# Research Question

How does the presence of fast food restaurants and other food establishments correlate with obesity rates in adolescents?

# Setup

In [1]:
## YOUR CODE HERE
import pandas as pd

# Path to the first local CSV file
file_path = 'E:\\mattd\\Desktop\\ProjectData\\Table_1.csv'

# Read the CSV data into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first 20 rows of the DataFrame
df.head(20)

,<b>Presence of establishments</b>,<b>Total</b>,Unnamed: 2,<b>Not overweight/Obese</b>,Unnamed: 4,<b>Overweight/Obese</b>,Unnamed: 6,<b>p-value</b>,<b>Unadjusted OR</b>,<b>95%CI</b>
0,NaN,n,%,n,%,n,%,NaN,NaN,NaN
1,Fast food restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,473,93.9,336,71.0,137,28.9,0.25,1.00,0.90-5.61
3,Yes,31,6.1,19,61.3,12,38.7,NaN,2.25,NaN
4,"Markets, supermarkets and grocery stores",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No,73,14.5,53,72.6,20,27.4,0.71,1.00,0.71-2.77
6,Yes,431,85.5,302,70.0,129,30.0,NaN,1.40,NaN
7,Bakeries and cafeterias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,No,451,89.5,315,69.8,136,30.2,0.39,1.00,0.36-2.18
9,Yes,53,10.5,40,75.5,13,24.5,NaN,0.88,NaN
10,Restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,No,123,24.4,87,70.7,36,29.3,0.93,1.00,0.40-2.05
12,Yes,381,75.6,268,70.3,113,29.7,NaN,0.91,NaN
13,Pizzerias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,No,387,76.8,270,69.8,117,30.2,0.55,1.00,0.61-1.95
15,Yes,117,23.2,85,72.6,32,27.4,NaN,1.09,NaN
16,Street markets and whole food markets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,No,249,49.4,175,70.3,74,29.7,0.94,1.00,0.68-1.70
18,Yes,255,50.6,180,70.6,75,29.4,NaN,1.07,NaN

In [2]:
# Path to the second local CSV file
file_path2 = 'E:\\mattd\\Desktop\\ProjectData\\Table_2.csv'

# Read the CSV data into a pandas DataFrame
df2 = pd.read_csv(file_path2)

# Display the first 20 rows of the DataFrame
df2.head(20)

,<b>Presence of establishments</b>,<b>Total</b>,Unnamed: 2,<b>Not overweight/Obese</b>,Unnamed: 4,<b>Overweight/Obese</b>,Unnamed: 6,<b>p-value</b>,<b>Unadjusted OR</b>,<b>95%CI</b>
0,NaN,n,%,n,%,n,%,NaN,NaN,NaN
1,Fast food restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,473,93.9,336,71.0,137,28.9,0.25,1.00,0.90-5.61
3,Yes,31,6.1,19,61.3,12,38.7,NaN,2.25,NaN
4,"Markets, supermarkets and grocery stores",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No,73,14.5,53,72.6,20,27.4,0.71,1.00,0.71-2.77
6,Yes,431,85.5,302,70.0,129,30.0,NaN,1.40,NaN
7,Bakeries and cafeterias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,No,451,89.5,315,69.8,136,30.2,0.39,1.00,0.36-2.18
9,Yes,53,10.5,40,75.5,13,24.5,NaN,0.88,NaN
10,Restaurants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,No,123,24.4,87,70.7,36,29.3,0.93,1.00,0.40-2.05
12,Yes,381,75.6,268,70.3,113,29.7,NaN,0.91,NaN
13,Pizzerias,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,No,387,76.8,270,69.8,117,30.2,0.55,1.00,0.61-1.95
15,Yes,117,23.2,85,72.6,32,27.4,NaN,1.09,NaN
16,Street markets and whole food markets,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,No,249,49.4,175,70.3,74,29.7,0.94,1.00,0.68-1.70
18,Yes,255,50.6,180,70.6,75,29.4,NaN,1.07,NaN

# Data Cleaning

Describe your data cleaning steps here.

In [3]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

# Check for missing values
print(df.isnull().sum())
print(df2.isnull().sum())

# Fill missing values with the mean of the column
df = df.fillna('')
df2 = df2.fillna('')

# Remove HTML tags from column names
df.columns = df.columns.str.replace('<b>', '').str.replace('</b>', '')
df2.columns = df2.columns.str.replace('<b>', '').str.replace('</b>', '')

#For df:
# Drop unecessary rows for observation
df.drop(range(4, 23), axis=0, inplace=True)

#For df2:
# Create a dictionary with current column names as keys and new column names as values
rename_dict = {'Unnamed: 2': '', 'Unnamed: 4': '', 'Unnamed: 6': ''}

# Use the rename() function to rename the columns
df2 = df2.rename(columns=rename_dict)

# Display the first cleaned DataFrame
df.head(20)

<b>Variables</b>                1
<b>Total population</b>         7
<b>Not overweight/Obese</b>     7
<b>Overweight/Obese</b>         7
<b>p-value</b>                 16
dtype: int64
<b>Presence of establishments</b>     1
<b>Total</b>                          6
Unnamed: 2                            6
<b>Not overweight/Obese</b>           6
Unnamed: 4                            6
<b>Overweight/Obese</b>               6
Unnamed: 6                            6
<b>p-value</b>                       13
<b>Unadjusted OR</b>                  7
<b>95%CI</b>                         13
dtype: int64

,Variables,Total population,Not overweight/Obese,Overweight/Obese,p-value
0,,n (%),n (%),n (%),
1,"Age (years, n = 504)",,,,0.07
2,12-15,259 (51.4),173 (66.8),86 (33.2),
3,16-19,245 (48.6),182 (74.3),63 (25.7),

In [4]:
# Display the second cleaned DataFrame
df2.head(20)

,Presence of establishments,Total,,Not overweight/Obese,,Overweight/Obese,,p-value,Unadjusted OR,95%CI
0,,n,%,n,%,n,%,,,
1,Fast food restaurants,,,,,,,,,
2,No,473,93.9,336,71.0,137,28.9,0.25,1.0,0.90-5.61
3,Yes,31,6.1,19,61.3,12,38.7,,2.25,
4,"Markets, supermarkets and grocery stores",,,,,,,,,
5,No,73,14.5,53,72.6,20,27.4,0.71,1.0,0.71-2.77
6,Yes,431,85.5,302,70.0,129,30.0,,1.4,
7,Bakeries and cafeterias,,,,,,,,,
8,No,451,89.5,315,69.8,136,30.2,0.39,1.0,0.36-2.18
9,Yes,53,10.5,40,75.5,13,24.5,,0.88,
10,Restaurants,,,,,,,,,
11,No,123,24.4,87,70.7,36,29.3,0.93,1.0,0.40-2.05
12,Yes,381,75.6,268,70.3,113,29.7,,0.91,
13,Pizzerias,,,,,,,,,
14,No,387,76.8,270,69.8,117,30.2,0.55,1.0,0.61-1.95
15,Yes,117,23.2,85,72.6,32,27.4,,1.09,
16,Street markets and whole food markets,,,,,,,,,
17,No,249,49.4,175,70.3,74,29.7,0.94,1.0,0.68-1.70
18,Yes,255,50.6,180,70.6,75,29.4,,1.07,

In [5]:
# Check again for missing values
print(df.isnull().sum())
print(df2.isnull().sum())

Variables               0
Total population        0
Not overweight/Obese    0
Overweight/Obese        0
p-value                 0
dtype: int64
Presence of establishments    0
Total                         0
                              0
Not overweight/Obese          0
                              0
Overweight/Obese              0
                              0
p-value                       0
Unadjusted OR                 0
95%CI                         0
dtype: int64

# Data Analysis & Results (EDA)

Carry out EDA on your dataset(s); Describe in this section

In [3]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION